In [2]:
%pip install scikit-learn numpy pandas matplotlib

Note: you may need to restart the kernel to use updated packages.


In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression as SklearnLogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import numpy as np
from source.logistic_regression import LogisticRegression

X, Y = load_breast_cancer(return_X_y=True)
Y[Y == 0] = -1

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [2]:
model_nr = LogisticRegression(solver='nr', max_iter=200, tol=1e-3)
model_nr.fit(X_train, y_train)

y_pred_nr = model_nr.predict(X_test)

print("Newton-Raphson Method:")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_nr))
print()
print(f"Accuracy: {accuracy_score(y_test, y_pred_nr):.3f}")
print(f"Precision: {precision_score(y_test, y_pred_nr, average='weighted'):.3f}")
print(f"Recall: {recall_score(y_test, y_pred_nr, average='weighted'):.3f}")
print(f"F1-score: {f1_score(y_test, y_pred_nr, average='weighted'):.3f}")

Newton-Raphson Method:
Confusion Matrix:
[[61  2]
 [10 98]]

Accuracy: 0.930
Precision: 0.935
Recall: 0.930
F1-score: 0.931


/Users/uvuv/ML_Algorithms/students/zinatulin-av/lab5/source/logistic_regression.py:14: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


In [3]:
model_irls = LogisticRegression(solver='irls', max_iter=200, tol=1e-3)
model_irls.fit(X_train, y_train)

y_pred_irls = model_irls.predict(X_test)

print("IRLS Method:")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_irls))
print()
print(f"Accuracy: {accuracy_score(y_test, y_pred_irls):.3f}")
print(f"Precision: {precision_score(y_test, y_pred_irls, average='weighted'):.3f}")
print(f"Recall: {recall_score(y_test, y_pred_irls, average='weighted'):.3f}")
print(f"F1-score: {f1_score(y_test, y_pred_irls, average='weighted'):.3f}")

IRLS Method:
Confusion Matrix:
[[ 57   6]
 [  3 105]]

Accuracy: 0.947
Precision: 0.947
Recall: 0.947
F1-score: 0.947


In [4]:
sklearn_model = SklearnLogisticRegression(max_iter=200, random_state=42)
y_train_sklearn = (y_train + 1) / 2
y_test_sklearn = (y_test + 1) / 2
sklearn_model.fit(X_train, y_train_sklearn)

y_pred_sklearn = sklearn_model.predict(X_test)
y_pred_sklearn = y_pred_sklearn * 2 - 1

print("Sklearn Logistic Regression:")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_sklearn))
print()
print(f"Accuracy: {accuracy_score(y_test, y_pred_sklearn):.3f}")
print(f"Precision: {precision_score(y_test, y_pred_sklearn, average='weighted'):.3f}")
print(f"Recall: {recall_score(y_test, y_pred_sklearn, average='weighted'):.3f}")
print(f"F1-score: {f1_score(y_test, y_pred_sklearn, average='weighted'):.3f}")

Sklearn Logistic Regression:
Confusion Matrix:
[[ 58   5]
 [  1 107]]

Accuracy: 0.965
Precision: 0.966
Recall: 0.965
F1-score: 0.965


In [ ]:
print("Comparison:")
print(f"Newton-Raphson Accuracy: {accuracy_score(y_test, y_pred_nr):.3f}")
print(f"IRLS Accuracy: {accuracy_score(y_test, y_pred_irls):.3f}")
print(f"Sklearn Accuracy: {accuracy_score(y_test, y_pred_sklearn):.3f}")
print()
print(f"NR vs Sklearn difference: {abs(accuracy_score(y_test, y_pred_nr) - accuracy_score(y_test, y_pred_sklearn)):.3f}")
print(f"IRLS vs Sklearn difference: {abs(accuracy_score(y_test, y_pred_irls) - accuracy_score(y_test, y_pred_sklearn)):.3f}")
print(f"NR vs IRLS difference: {abs(accuracy_score(y_test, y_pred_nr) - accuracy_score(y_test, y_pred_irls)):.3f}")

Comparison:
Newton-Raphson Accuracy: 0.930
IRLS Accuracy: 0.947
Sklearn Accuracy: 0.965

NR vs Sklearn difference: 0.035
IRLS vs Sklearn difference: 0.018
NR vs IRLS difference: 0.018
